title: Ronald Laforet
email: kimberly@ronaldlaforet.com
description: Tech Blogger, Strategist, Visionary. Le Elon du Nord.
baseurl: ""
url: "https://ton-username.github.io"

author_name: Ronald Laforet
tagline: "Tech Blogger • Strategist • Visionary"
location: "3877 Rue de la Citrouille, Malheurville, ON"